stages:
  - install
  - test
<<<<<<< HEAD
=======
  # - deploy
>>>>>>> 2ff3c7eb3fb9b2b80d995963802dafd0f7f6249b

# Install dependencies
install_dependencies:
  stage: install
  image: node:16
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Run tests
test:
  stage: test
  image: node:16
  services:
    - name: mongo:latest
      alias: mongo
  script:
    # - npm run lint
    - npm run test
  artifacts:
    paths:
      - coverage/
  only:
    - main
