version: "3.8"

services:
  app:
    build: .
    container_name: node-express-app
    depends_on:
      - rabbitmq
    environment:
      - MONGO_URI=mongodb+srv://newuser:rening007@crud.057ti.mongodb.net/node-graphql
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "dev" ]

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  # worker:
  #   build: .
  #   container_name: node-express-worker
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #   command: [ "npm", "run", "worker" ]
